### ISSUE TITLE
`np.bool` is deprecated

### ISSUE THREAD

**Issue by manodeep** [qyx268/astrodatapy#12]
Encountered this error when trying out astrodatapy:

```python
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

There are three instances of `np.bool` in each of the files `correlation.py`, `clustering.py`, and `number_density.py`. Replacing `np.bool` with `bool` fixed the issue for me.

**Comment by qyx268** [comment]
I actually had this fixed in May but never pushed it. I'm reviewing what I've done before pushing it. But I'm closing this issue now
