### ISSUE TITLE
Baldry2008 does not show up for GSMF at z=0

### ISSUE THREAD

**Issue by manodeep** [qyx268/astrodatapy#14]
I am looking at the available datasets and looks like Baldry+2008 at z=0.0 is [available](https://github.com/qyx268/astrodatapy/tree/master/astrodatapy/data/GSMF/Baldry%2B2008) but there is no Baldry2008 in the astrodatapy list of returned datasets. 

```python
>>> obs    = number_density(feature='GSMF',z_target=0.0,quiet=False,h=0.7)

You are requesting GSMF at z_target=0.00 with a tolerance of z_tol=0.25 and h=0.700
quiet=True to silent
available data of GSMF includes:
Bell2003 Cole2001 Drory2009 Marchesini2009 Mortlock2011 Stefanon2017 Thanjavur2016 Grazian2015 Gonzalez2011 Duncan2014 Katsianis2015 Song2016 Davidzon2017 Santini2012 Ilbert2013 Muzzin2013 Huertas-Company2016 Tomczak2014 Pozzetti2007 Baldry2012 Caputi2011 Kajisawa2009 Perez-Gonzalez2008 Pozzetti2010 Yang2009 Qin2017_Tiamat Qin2017_Tiamat125_HR

...

```
There is the Baldry2012 [dataset](https://github.com/qyx268/astrodatapy/tree/master/astrodatapy/data/GSMF/Baldry%2B2012) - which looks to be at z=0.1, and has no comments in the datafile. 

@qyx268 Any ideas what is going on? Is this a data formatting issue in the Baldry2008 file?

**Comment by manodeep** [comment]
Is this [line](https://github.com/qyx268/astrodatapy/blob/master/astrodatapy/data/GSMF/info.txt#L17) why that Baldry2008 data is not returned? Superseded by Baldry2012 may be?

**Comment by qyx268** [comment]
Indeed. I had to review the 2012 paper again, which commented that the new results are more complete in terms of surface brightness. The two results are broadly consistent at >1e8.2 Msol. However, I must have kept the 2008 data because it is a different dataset from 2012 (SDSS vs preliminary GAMA)

**Comment by qyx268** [comment]
Let's chat tomorrow about what you guys are doing and I can then double check the number again. But I'm closing this issue now.

**Comment by qyx268** [comment]
Forgot to say. 2008 has z<0.05 while 2018 z<0.06...
