### ISSUE TITLE
column ordering of the errors

### ISSUE THREAD

**Issue by manodeep** [qyx268/astrodatapy#16]
Based on the example GSMF notebook, it seems that the code is expecting to find `ULLimits` in the error columns once the data has been read in. However, looking at [these lines](https://github.com/qyx268/astrodatapy/blob/0d717f5b3b01019f1335175f40921a8c8350e816/astrodatapy/number_density.py#L264-L268), I can see that the cases with `ULDelta/LUDelta/Delta` all get converted into the 1-sigma upper and lower limit. But I interpret those lines of code as the `ULDelta` gets mapped to `ULLimit` while `LUDelta` gets mapped `LULimit`. Is that not the case?

**Comment by qyx268** [comment]
Hah! But the 2 lines above reverse LUDelta or LULimit into ULDelta or ULLimit... I had weird writing styles back in the day.
