### ISSUE TITLE
Data Labels

### ISSUE THREAD

**Issue by madelinemarshall** [qyx268/astrodatapy#4]
Is it possible to print out data labels as "AuthorName et al. (Date)" or even "AuthorName (Date)"  instead of AuthorNameDate?

**Comment by qyx268** [comment]
This feature is not included. But you can do
[label[:label.rfind('20')]+'et al. ('+label[label.rfind('20'):]+')' for label in labels]

**Comment by madelinemarshall** [comment]
Perfect, that's exactly what I was after. Thanks!
