### ISSUE TITLE
BHMF h conversion

### ISSUE THREAD

**Issue by madelinemarshall** [qyx268/astrodatapy#5]
When I plot the BHMF I get the warning "Warning! Don't know how to convert h for x axis of BHMF". Why is that?

**Comment by qyx268** [comment]
Hah, it's because I really don't know how to. I left this information for future debugging... I will take a look this week and get back to you.

**Comment by madelinemarshall** [comment]
Thanks! I'll have a look into it too and let you know if I work it out :)
